blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.index,name='index',),
    path('posts/<int:pk>/',views.detail,name='detail'),
    path('archives/<int:year>/<int:month>',views.archive,name='archive'),
    path('categories/<int:pk>',views.category,name='category'),
    path('tags/<int:pk>',views.tag,name='tag'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('comments.urls')),
]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>',views.comment,name='comment'),
]

blog/models.py
import markdown
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.utils.html import strip_tags
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField('标题',max_length=70)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间',default=timezone.now)
    modified_time = models.DateTimeField('修改时间')
    excerpt = models.CharField('摘要',max_length=200,blank=True)
    category = models.ForeignKey(Category,verbose_name='分类',on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag,verbose_name='标签',blank=True)
    author = models.ForeignKey(User,verbose_name='作者',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']
    
    def __str__(self):
        return self.title
    
    def save(self,*args,**kwargs):
        self.modified_time = timezone.now()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:50]
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

comments/models.py
from django.db import models
from django.utils import timezone

class Comment(models.Model):
    name = models.CharField('名字',max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址',blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间',default=timezone.now)
    post = models.ForeignKey('blog.Post',verbose_name='文章',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
    
    def __str__(self):
        return '{}: {}'.format(self.name,self.text[:20])

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','url','text']

blog/views.py
import re
import markdown
from django.shortcuts import render,get_object_or_404
from .models import Post,Category,Tag

def index(request):
    post_list = Post.objects.all()
    return render(request,'blog/index.html',context={'post_list':post_list})

def detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    post.body = md.convert(post.body)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>',md.toc,re.S)
    post.toc = m.group(1) if m is not None else ''
    return render(request,'blog/detail.html',context={'post':post})

def archive(request,year,month):
    post_list = Post.objects.filter(created_time__year=year,
    created_time__month=month)
    return render(request,'blog/index.html',context={'post_list':post_list})

def category(request,pk):
    cate = get_object_or_404(Category,pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request,'blog/index.html',context={'post_list':post_list})

def tag(request,pk):
    t = get_object_or_404(Tag,pk=pk)
    post_list = Post.objects.filter(tags=t)
    return render(request,'blog/index.html',context={'post_list':post_list})

comments/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post
from django.views.decorators.http import require_POST
from django.contrib import messages

from .forms import CommentForm

@require_POST
def comment(request,post_pk):
    post = get_object_or_404(Post,pk=post_pk)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)

        comment.post = post

        comment.save()
        messages.add_message(request,messages.SUCCESS,'评论成功！',extra_tags='success')
        return redirect(post)

    context = {
        'post':post,
        'form':form,
    }
    messages.add_message(request,messages.ERROR,'评论失败！请修改表单中的错误后重新提交。',extra_tags='danger')
    return render(request,'comments/preview.html',context=context)

templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>晴耕雨读</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	<link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
	<style>
	  .codehilite {
	    padding:0
		}
	  .hljs-ln-number {
	    -webkit-touch-callout:none;
		-webkit-user-select:none;
		-khtml-user-select:none;
		-moz-user-select:none;
		-ms-user-select:none;
		user-select:none;
		
		text-align: center;
		color: #ccc;
		border-right: 1px solid #CCC;
		vertical-align: top;
		padding-right: 5px;
		}
	  .hljs-in-n {
	    width: 30px;
		}
	  .hljs-in .hljs-ln-code {
	    padding-left:10px;
		white-space:pre;
	  }
	  </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>晴耕</b>雨读</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
	{% if messages %}
	  {% for message in messages %}
	    <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-lable="Close"><span
		  aria-hidden="true">&times;</span></button>
		  {{ message }}
		</div>
	  {% endfor %}
	{% endif %}
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
			   {% block main %}
               {% endblock main %}			   
            </main>
            <aside class="col-md-4">
              {% block toc%}
              {% endblock toc %}			    
              {% show_recent_posts %}
			  {% show_archives %}
			  {% show_categories %}
			  {% show_tags %}
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>			  
            </aside>
        </div>
    </div>
</div>
<span class="back-top"><i class="ri-arrow-up-line"></i></span>
<footer class="bg-white py-5 mt-5 text-small text-muted">
  <div class="flex-center">
    <div>&copy; 晴日躬耕以果腹，雨夜闲读以悦心！</div>
  </div>
  <div class="flex-center">
    <div><a href="http://beian.miit.gov.cn/publish/query/indexFirst.action" target="_blank">粤ICP备20010731</a></div>
  </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
<body>

  <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>

  <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>

  <script>

    hljs.initHighlightingOnLoad();

    hljs.initLineNumbersOnLoad();

  </script>

</body>
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}
{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    
                        {% show_comment_form post %}
                        <div class="comment-list-panel">
                          {% show_comments post %}
                       </div>
                </section>
{% endblock main %}
{% block toc%}
    {% if post.toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
					<div>
					  <ul>
                        {{ post.toc|safe }}
					  </ul>
					</div>
                </div>
    {% endif %}
{% endblock toc %}

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
  <h3 class="width-title">归档</h3>
	<ul>
	  {% for date in date_list %}
		  <li>
		    <a href="{% url 'blog:archive' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a> 	
			</li>
		{% empty %}
		  暂无归档＝
		{% endfor %}		
	</ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
  <h3 class="width-title">分类</h3>
	<ul>
	  {% for category in category_list %}
		  <li>
		    <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span calss="post-count">(13)</span></a> 	
			</li>
		{% empty %}
		  暂无分类！
		{% endfor %}		
	</ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
  <h3 class="width-title">最新文章</h3>
	<ul>
	  {% for post in recent_post_list %}
		  <li>
		    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> 	
			</li>
		{% empty %}
		  暂无文章！
		{% endfor %}		
	</ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
  <h3 class="width-title">标签</h3>
	<ul>
	  {% for tag in tag_list %}
		  <li>
		    <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a> 	
			</li>
		{% empty %}
		  暂无标签！
		{% endfor %}		
	</ul>
</div>

templates/blog/index.html
{% extends 'base.html' %} 
{% block main %}

			  {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
			  {% empty %}
			    <div calss="no-post">暂时还没有发布的文章</div>
			  {% endfor %}

                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
{% endblock main %}
           

templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment'  post.pk %}" method="post" class="comment-form">
  {% csrf_token %}
	<div class="row">
	  <div class="col-md-4">
		  <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
			{{ form.name }}
			{{ form.name.error }}
		</div>
		<div class="col-md-4">
		  <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
			{{ form.email }}
			{{ form.email.errors }}
		</div>
		<div class="col-md-4">
		  <label for="{{ form.url.id_for_label }}">{{ form.url.label }}:</label>
			{{ form.url }}
			{{ form.url.errors }}
		</div>
		<div class="col-md-12">
		  <label for="{{ form.text.id_for_label }}">{{ form.text.label }}:</label>
			{{ form.text }}
			{{ form.text.errors }}
			<button type="submit" class="comment-btn">发表</button>
		</div>
	</div>
</form>

templates/comments/inclusions/_list.html
<h3> 评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
	  <li class="comment-item">
		  <span class="nickname">{{ comment.name }}</span>
			<time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
			<div class="text">
			  {{ comment.text|linebreaks }}
			</div>
		</li>
	{% empty %}
	  暂无评论！
	{% endfor %}
</ul>

templates/comments/preview.html
{% extends 'base.html' %}
{% load comments_extras %}
{% block main %}
  {% show_comment_form post form %}
{% endblock %}